import hydraAPI from 'api/hydra';

export const GET_HYDRA_SERVICES_STATUS_START = 'GET_HYDRA_SERVICES_STATUS_START';
export const GET_HYDRA_SERVICES_STATUS_SUCCESS = 'GET_HYDRA_SERVICES_STATUS_SUCCESS';
export const GET_HYDRA_SERVICES_STATUS_FAILURE = 'GET_HYDRA_SERVICES_STATUS_FAILURE';


export function getHydraServicesStatus() {
  return {
    types: [GET_HYDRA_SERVICES_STATUS_START, GET_HYDRA_SERVICES_STATUS_SUCCESS, GET_HYDRA_SERVICES_STATUS_FAILURE],
    promise: hydraAPI.getHydraServicesStatus()
  };
}

export const GET_HYDRA_COMMAND_STATUS_START = 'GET_HYDRA_COMMAND_STATUS_START';
export const GET_HYDRA_COMMAND_STATUS_SUCCESS = 'GET_HYDRA_COMMAND_STATUS_SUCCESS';
export const GET_HYDRA_COMMAND_STATUS_FAILURE = 'GET_HYDRA_COMMAND_STATUS_FAILURE';

export function sendHydraCommandMessage(message) {
  return {
    types: [GET_HYDRA_COMMAND_STATUS_START, GET_HYDRA_COMMAND_STATUS_SUCCESS, GET_HYDRA_COMMAND_STATUS_FAILURE],
    promise: hydraAPI.sendHydraCommandMessage(message)
  };
}
